name: Upload Python Package

on:
  push:
    branches:
      - master
    paths:
      - "fgo_api_types/**"
      - "app/schemas/*.py"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Build package
        run: |
          cp app/schemas/*.py fgo_api_types/fgo_api_types/
          cd fgo_api_types
          poetry version $(date -u +"%Y.%m.%d.%H.%M.%S")
          poetry build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: fgo_api_types/dist/*.whl
      - name: Upload to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        working-directory: ./fgo_api_types
        run: |
          poetry config http-basic.pypi "__token__" "$POETRY_PYPI_TOKEN_PYPI"
          poetry publish
